### ISSUE TITLE
[BUG] Filesystem fetcher doesn't work with slash character

### ISSUE THREAD

**Issue by sebacrgithub** [ercole-io/ercole-agent#202]
**Describe the bug**
Error on ercole-agent-exadata - fetch/host phase. 
If is present some backslash the fetch phase doesn't work:
ex. \\vnet1\pippo/Pluto

Sep 21 12:34:11 oraexa0a.mil.esselunga.net ercole-agent-exadata[343904]: 2020/09/21 12:34:11 Fetching host:
Sep 21 12:34:12 oraexa0a.mil.esselunga.net ercole-agent-exadata[343904]: 2020/09/21 12:34:12 Fetching filesystem:
Sep 21 12:34:12 oraexa0a.mil.esselunga.net ercole-agent-exadata[343904]: 2020/09/21 12:34:12 invalid character 'P' in string escape code
Sep 21 12:34:12 oraexa0a.mil.esselunga.net systemd[1]: ercole-agent-exadata.service: main process exited, code=exited, status=1/FAILURE
Sep 21 12:34:12 oraexa0a.mil.esselunga.net systemd[1]: Unit ercole-agent-exadata.service entered failed state.
Sep 21 12:34:12 oraexa0a.mil.esselunga.net systemd[1]: ercole-agent-exadata.service failed.

**Expected behavior**
No errors even backslashes are present

**To Reproduce**
...

**Screenshots, logs, stdout, stderr, asciinema**
...

**Desktop (please complete the following information):**
 - OS: [RedHat 7]
 - ercole-agent-exadata version: ercole-agent-exadata-1.6.3-1.el7.x86_64 and below 

**Additional context (optional)**

**Possible solution (optional)**

**Comment by amreo** [comment]
From the bug description it seems me that ercole-agent-exadata stopped in the fetch/filesystem phase.
Can you post fetch/filesystem output?
```
cd /opt/ercole-agent-exadata
fetch/filesystem
```

**Comment by amreo** [comment]
Does this bug still affect ercole latest?

**Comment by amreo** [comment]
old filesystem marshaller: https://github.com/ercole-io/ercole-agent-exadata/blob/master/marshal/filesystems.go
new filesystem marshaller: https://github.com/ercole-io/ercole-agent/blob/master/marshal/filesystem.go

I think no because the "new" filesystem marshall doesn't unmarshal the filesystem making and unmarshalling the JSON but splitting the lines. So I think this bug can be classified as "wont fix" and closed. A work around to this bug may be adding a sed to   the filesystem fetcher that replace the backward slash '\' with '\\' or other symbol.
